language: objective-c
osx_image: xcode9.4
install:
- bundle install
script:
- fastlane beta
before_script:
- "./scripts/add-key.sh"
env:
  global:
  - APP_NAME=cicd-test
  - DEVELOPER_NAME="iPhone Distribution: Nascent Digital Experiences Inc (9SNZ8X3UFW)"
  - PROFILE_NAME=cicdadhocdistributionprofile
  - KEY_PASSWORD=Password123
  - secure: gJk18zda3Q/M+RmX8AzngJtc37UAeY70qC76HDeVXWVlBMrmI3VbYFuTgASqAEx88brLLtpLXijF2ZWlXM8Rx37fcXAr7/1NoE8OG9tfNQHfprrL2Hv09bEHXxAxdzomiQHrTeSER9JSI96wW6Xl8OtQs/BzL8vY7JbAgwEUeMXAEY7sOcr7OqrZHUP4vN8TKlLGfk9KiLWICNYl/OfkiMOmue2UAWIjHM/I2HeiIImlFBnfsAiUmj67Zh+6JgLDpWIX0mVLK86jwYqi0TE1/XYy/pgLR1gmKL5FKtrQKsayixBbSWuk/TOt85bvp2QBtePkbdEOgPnVVX156eZpJifHgGQ3BAbg/WLZZZc55cBmTW6ikweEdkwMqOFw0B6bFcgjSpRpeDoLgZChFjRyMwRi4jnWiNT+dDcbWttrb7tkZg5l4jYB/Kq9SxamRbgxkM16bD/Vg+mZjufQyoYivYHwo45likJguguljA2av/PlJj+PUXLjnsLCBP8xbDjEIK3FddhUmnHYZN0S4fFiSuPa+qTVnQXbRMViDQg+h3Be6/gGVSQvHiGYQz5awCn91T7gyJe2xQ24tcdmgQWDfvTM87shr4Sz8ilkXj3liX9i0rfyvGuO4A6jfDmYOq0uHPtFKZuzdAB0apctP7+cn7Ky6cGhzF7jSP7xPVp5fkE=
before_install:
- openssl aes-256-cbc -k password_key -in certs.tar.enc -out certs.tar -d
- tar xvf certs.tar
