language: objective-c
osx_image: xcode9.4.1
install:
- bundle install
script:
- fastlane beta
before_script:
- "./scripts/add-key.sh"
env:
  global:
  - APP_NAME="cicd-test"
  - 'DEVELOPER_NAME="iPhone Distribution: Nascent Digital Experiences Inc (9SNZ8X3UFW)"'
  - PROFILE_NAME="cicdadhocdistributionprofile"
  - KEY_PASSWORD="Password123"
before_install:
  - echo $encrypted_18cf317e13f3_iv
  - echo $encrypted_18cf317e13f3_key
  - openssl aes-256-cbc -k password_key -in certs.tar.enc -out certs.tar -d
  - tar xvf certs.tar
