language: objective-c
osx_image: xcode8.3
install:
- bundle install
script:
- fastlane beta
before_script:
- "./scripts/add-key.sh"
env:
  global:
  - APP_NAME="cicd-test"
  - 'DEVELOPER_NAME="iPhone Distribution: Nascent Digital Experiences Inc (9SNZ8X3UFW)"'
  - PROFILE_NAME="cicdadhocdistributionprofile"
  - secure: hnkdDWfY2YRPv8nuAHUvBkXEBlrG2dhhH+EL0yqukoN/3P7obhIzJCIbDFrUh17jLrSdLr3K/+xoe0hPKWK6ZeZPYMidk1teHTGaYDpv+Iy5OePPV5T5MFOyaREppIQCuXCCSIX7bDMb070ODpcZADaKUWLhpkYoaFs6J8hTsiBTVFYG0iUccUsyXG1ctlY7jxUicAt4Gnq32QSxrUJQhdlke77jSkezs7kaHfrYrdOqqxZ4TL0aiYeWDOfhFL9M1SGv863o+5NiYwHmBibZJjhcfzlAF8BNtQvC3amIUN8LZkQDsU3Sx0w5Zq5JJEa6YpmHsHIx4M8XbpVx9RkP0hcCXa8WYb76nZ0e90azPBPezHPrjuAr4MoNztM2zr/HW5I50NDQBXYnUnBWf2zARLmL3qAG5eqKZO58bD7F/xwNqnrVHda93x3B7gz4XBmbkGNgtZsNmhwxbnQZffxThuQrTgF/Syw6UKrLiR1GYPOuHOOunMWixXlJZKbJ15FjoxdZACgUCNAve6fXe3CtvEu4S8YGWvpCtj87KQ1a3s3xdoTlGt7FYLaMtoOr7eP2aFv1NF4mgxeKsmWgGvGPhEXINXCGM3ID+O4KJ3MeEj6kIqZZPoa1yfbi2hjNBx5WZtLLc/zt/I8Mg3Xr6ZqOAwbhtIdpcyVvXnMOdL2xE/k=
  - secure: gnC3xFwX26wS3AnRMMnaSusex6mVltOmZzrR2iwbGp/JMwt2u41zMty2vdu3s8HqpwIzsgY8Xspt7j0D4P9Qnf/EwZb+zLtxdfYLsK6XM1rqSvNQP/9dVPElbMN+Kfj4RtFpfvwBk6QFmUSkHr7RzDcWBi/QwXrrK5HAFZYNa8Q+rieVogfUj3znwvrhEjp+hN+yI3yowbqy+KpMDK07vuo0VsXxSKnEFSzkqrBWy8D+BiN3oNomWuWkjbl+HBxptcb9Hc2KwbqLjXetjGTeD5w9YzqGW/gGdf2Qh4ASYgtYbutRW44cFS/n6gpjy8y37ZUG2KsZK0m9JyeRpqT+NRWEJ4ENopF6KznLWqXfxERsRs/c4RXgQXKxatj3ZzbM2uEGsEtWHrBvf36uTzxyRz6ZaEHHOB9mUmHW+/lEkkvxCJuTFw4yww7vZiCBfLooahNt8EPtVxfMZYC/aRycVbOGf8fIM8pJ5NtRSATljUS/3WGyZdmxa07UyrwP8V8vzsHIZdI2oOhbCwl3OKOZzZNputGmUfz48WzsHrWptb1yxhLQyUclUNkmD74FMBxARAXoyfzyF4b2v2rshBw+hzNuN9qyNQgqvQjbtg0vyL1RbdOBJCYNwA+DU25yeRVjmnCq8jMNRl/XJwoBkfLa+0Mu/ApdCqFtNHcH86DlRbs=
before_install:
- openssl aes-256-cbc -K $encrypted_18cf317e13f3_key -iv $encrypted_18cf317e13f3_iv
  -in certs.tar.enc -out certs.tar -d
- tar xvf certs.tar
