language: objective-c
osx_image: xcode8.3
install:
- bundle install
script:
- fastlane beta
before_script:
- "./scripts/add-key.sh"
env:
  global:
  - APP_NAME="cicd-test"
  - 'DEVELOPER_NAME="iPhone Distribution: Nascent Digital Experiences Inc (9SNZ8X3UFW)"'
  - PROFILE_NAME="cicdadhocdistributionprofile"
  - secure: b1supXa/iYZ6ZgU4Rr7vqXgAyWwNQfnfd2JsoPhSgBigEFzsyvGsWlYtnZ0kEbx9l0zuDojmdd7QaJp5UkxB9GdiGYLDv4nivuPxGAfLXIzLqSb3hI3EWUVzIH/MV4q4gDrf1gZp/3vQDkbN+AEUHUfVOQMgq/A3kBJW6/xXBWbotRKbPehGXzPSdVc0cd0OifcTM5BB4EVNuN5IBZJWCYNzx+ObF5jHfeORrL60jfFRPRJdbc7+GkSY0CU5Xb+ykwxCie3sn+2oshQErjNJr10O6Twrg53+EPV1AgOg3AdnccafSCk29v0s+L9YS0feHF8+eAYBYcIqqM226GFJR1aUJYENVqnDXgAAELGSC4ir9LzPMdXqpcIM1KxT2s+/BX1au04GHaqFPxRfensdkv572MLdxhRaLSA0vqCV7bIsLbzYX7b9sPMx6wfOp0oDiI1n4TBTj0UvzvK2YCpXaoBxQFIdwn4wpfFMlCqGr3JssZecxhKRibk1pIg/jpnoiy40WtJVcwSMnV4acELB0wWRv6bTIqre38e4e5aliQUenbgO8t1JVkZNg+hfHREzVDDhZvxjUdLn8yWrY/2EV/yROlawisfWl/DzcGThy4qGBNiG6BLBIAeiuAfgUQoarQyqcx4bJnpxBwvAK1TdbZwig30xl7sGoqOJJrUSouA=
before_install:
  - echo $encrypted_18cf317e13f3_iv
  - echo $encrypted_18cf317e13f3_key
  - openssl aes-256-cbc -k password_key -in certs.tar.enc -out certs.tar -d
