language: objective-c
osx_image: xcode9.4
install:
- bundle install
script:
- fastlane beta
before_script:
- "./scripts/add-key.sh"
env:
  global:
  - APP_NAME=cicd-test
  - DEVELOPER_NAME="iPhone Distribution: Nascent Digital Experiences Inc (9SNZ8X3UFW)"
  - PROFILE_NAME=cicdadhocdistributionprofile
  - KEY_PASSWORD=Password123
  - secure: h2HkpeWqlhUrhNazsSG4IVSjg4NW1yktChyMRaYOBQsyXuRkwffGuPwFdWBf0n0Bx1C7PPPUjN3CdIP/OXhmOltGPek6mSY+EyyZLLRJdVtpQoGufd5PAl8RiRKtd1HLho7uX9LRfEYoWQsKFqUn7NIiBwJY+h63oWbOhdlOd+MsotPaolHGZ/JLN1UGbeakLAgZ9ZAd51cyplp9ITdk1rOSvzMAGIHrbXjkXF179WETdQLxzc1cNVuLfPELXGrJWvklk97esvsVotGCnmxM00kJZW2iNRqOoq/8k6Uj1jqJ2csXHYdRnAfmNd1vxPhtGFtuNcev27jJXm0Jw6OqR2N9eaQBpB+VL9funCvRm/oIHsMgHz4tHmeUHMa5mvuR8WoXAt8W6YrG77NPDeKuVyzkK50fEKRICk5WDgVhj9Tn3FOaUTqTAmZI/VHuTZPlvEMFyaWqsOKc7s8d1PMaZzjqW/tcS4EqNFtnOWWt/5cocRmD9LclOl8RBrMpgDNMAxJK6S5qFBp1wF6mGu5pmcqbH5J2DJ1Y9Vnb0T/OfZN3aJJcV1tx64uggWYUkk0EzeaNP5HfexKVM3CQ6k/RZGH0BUf5U1PqtX4VQ9WYYBNp0+ErziutsU0gDf2YO3Qu1Y86vZWxsX945l0n5izvUomJiqs3GjYXze/LmDdEwbU=
  - secure: gF+oUxFMaOjTqZB2e1oaB4RNKMX62+yx69GrBuJ9AAzbw7Fxk/Xp9YjKylT7h2Sl0KdGBBet6/ArX6EEzv34UX/t2Jd1EBVdJsBnPue7D/XiVAz5e5U5YxuDQvNZ6LLGsAGGSS9StNYFyYRfPwGTPSN5SefqrgreBPHzRqCJf62onk6y/24yZCZ023acA7xEimuxJKQ3lREJtvnTWBU6rLJ6RC+SH99MmqBxr0LBFTziDPnPzgQa772SRDcNTzg5Bcl7na3M8bOKdOztUIuQPcvoOiDr6/tU8I8uJCGn0zDNaG8Kb79i60gTYhINJRCLhHLZ3nJRoRzMQVjI8EwHvR6CpjVQG0fQ0s67OWGZTvw8/eHSNFxjnGD3CCzA5PFiyk6XDEQRleP1cON8AG8XzkpFno90f1gplr1svMOR0mrfVMa/H77ZDpeTS/Rcp7cVidj/nB+J3nvmFFaIo6gy2PrSEz/9ZIkT9ZyIYL94aKvuyrqLY6owN1rVHF81HZ0cAh+GEXssitjC4CvBrkNB1LAC9hxBJljPKMPgrX5JsC0hwWSMUua8HxQaTfJ7t6ELaHqi7Ta6CULSonBZjmc+9/QwnTNEnZSlSx5VJPHTO/Az0PaG1QV9O/PXsPv73SP6i3SFfjXYau+NGmJXsUl+GDd4EyLL1HcDeFDfASlJJiU=
  - secure: b903ecpM6ES96tVnm6gNmuaoWxVcopd/45kgUb5Tkqi4q3FKQ24zikJ4vCDkbhVnURkLyANLGnz/WmFpQukHgvLAobyfBghKTy/BsdXHvPz3NrDoJoMvJMYU9ww2wx/eHBUvBRg89oZeYeAdZzj6xCR6TGHSDbe03VHcCQ602o7wgE67u5zAs4142MGZAEftYJ5Id28cYA7TfGLSgkHg7/8hhkxhdZ5S9UxJZtFl7lKv+Piofwh25e3TH+veWkjJjkwTzRszUqqxpcdNx/7cOOL4q1/lR2148QkkxV1UBhWxY7jaUBkiTWR1rp/gjCjxHtT5kljnt/pi0ddpFYzNjOaAAqCWjBCG4sx7YS/dRD7G1t6NuBWbFne4Hd2lEB0iIUa+AoStEHblU532sXYkvTsVJXrqUbQERGqve0vP9I1d1/OR7IUG+Rr5VOuxP/JZi9QwoEIBF2HyjlstKOkDfpCb+HdNwymBmaoKR7DzcNs76MvC0rwBbeIXqEGZjJ3518KdZt99oEm3hC1JX3sDidobUR2Wp1G6TxC8eiZpFUO7q2VsJdKljUEsBRXlgiAB/vwtSONyBHJVnycejWQLEwvCx3TK1ulDUV3gKEO67CucCeYLwocAEk5OfKBQkBNq8bQ0LNddp+6BKFHDYgPBWYcBRRACWl/C+zEHuwhXDZg=
  - secure: Z8yDBrToYZV43XCVuH4PGYugmEnIvD6aTAU7itPCzmQDMp0fTbZYlM+4OAmcT/xN1cZ5yx+jPUAUipfxnCJiBU9JSUqhbvJ/1iNvR8z9evMVrGDyDwtjU/7LaywWL/LUElAsOd9SetsjSdI1O5nElEvzp7dtKRPQkRmFFfVc+m5ZAaHWfkC61G4pIihDQKVSfxEFf3RKpjqykWECTPWL9trOzp70MPFX5VNl8KXs0ywF7FdMRgWdbqp+NR5wPBF69eLgALrqd+nBFMspW6e4wQegc6Vo/dM5Bg4yvof0fEdzVD3hxCSr3DKIbjtwYOROqMXdMqPbCrC5E5Zi1IKv8iNPqrF6kUZYhOQUeghvz9IApD1L5gzvXrNd5LSQaHc4YWaPLs19pWDYgmFcGaIJnIm5XviB6fU2ghJAuJpin60LJuIWkHSFXU1meGNFPOYBDWtsCc0zdSsgImowlzmwVmzQuKi1kZDQ7EwRLbWJ0NFQ35TRVJGbABKh84SlxqefAHmdH6c13aVnAom1zWNLNW8tMHkMUA9Pt+GEid/JMa1Uw3GCr0y2JWKHRYlN1JROtQ7/EIN7CY+ecxmHoxKnEpVrDWz7gT5+K5lfGnqOnAhOies5eKdsedHIaKvYBnrGHPgmFDr4Yd/2eteClQY7FTCfKmQhPGW1NZWB9B/vjPg=
before_install:
- echo $encrypted_18cf317e13f3_iv
- echo $encrypted_18cf317e13f3_key
- echo $RANDOM_ENCRYPT
- echo $SOMEVAR
- echo $SOME_OTHER_VAR
- echo $TESTVAR
- echo $vjPg
- echo NEXT SHOULD WORK
- echo $KEY_PASSWORD
- openssl aes-256-cbc -k password_key -in certs.tar.enc -out certs.tar -d
- tar xvf certs.tar
