# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    disable_automatic_code_signing(path: "cicd-test.xcodeproj")
  	build_app(export_method: "ad-hoc")
    enable_automatic_code_signing(path: "cicd-test.xcodeproj")
    hockey(api_token: "74f8a6a194ee48dead825eb2fdf0554a")
  end
end